version: 2

defaults: &defaults
  docker:
    - image: circleci/node:13.3.0
  working_directory: ~/workspace

jobs:
  fetch:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Node version
          command: node -v
      - run:
          name: Fetch deps
          command: yarn
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths: .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: yarn build
      - run:
          name: Types
          command: yarn types
      - run:
          name: Docs
          command: yarn docs
      - persist_to_workspace:
          root: ~/workspace
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Lint
          command: yarn lint

  artifacts:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: types
      - store_artifacts:
          path: examples
      - store_artifacts:
          path: docs

  deploy-master:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/workspace/.npmrc
      - run:
          name: Publish
          command: npm publish

  deploy-nightly:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/workspace/.npmrc
      - run:
          name: Version
          command: npm version $(node ./utils/push-nightly-tag.js)
      - run:
          name: Publish
          command: npm publish

  gh-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Push to gh-pages
          command: yarn gh-pages

workflows:
  version: 2
  inspection:
    jobs:
      - fetch
      - build:
          requires:
            - fetch
      - lint:
          requires:
            - fetch
      - artifacts:
          requires:
            - build
      - deploy-master:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/
      - gh-pages:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "4 20 * * *"
          filters:
            branches:
              only:
                - dev
    jobs:
      - fetch
      - build:
          requires:
            - fetch
      - artifacts:
          requires:
            - build
      - deploy-nightly:
          requires:
            - build
