name: Init

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
