name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Lint
      run: npm run lint-ci

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Test
      run: npm run test -- --coverage
    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: |
          coverage/

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Build
      run: npm run build
    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          dist/
          ts*/
          types/

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Download Builds
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Build Docs
      run: npm run docs
    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          docs/

  gh-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
    - build
    - docs
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Download Builds
      uses: actions/download-artifact@v4
      with:
        name: build
        path: public
    - name: Download Docs
      uses: actions/download-artifact@v4
      with:
        name: docs
        path: public/docs
    - name: Copy Examples
      run: |
        cp -r examples public/examples
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
